language: rust
matrix:
  include:
    - os: linux
      rust: stable
      dist: trusty
    - os: linux
      rust: nightly
      dist: trusty
    - os: osx
      rust: stable
    - os: osx
      rust: nightly
sudo: true
env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
addons:
  apt:
    packages:
    - libgsl0-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl; fi
script:
  - rustc --version
  - cargo check
  - cargo check --features v2_1
  - cargo check --features v2_2
  - cargo check --features v2_3
  - cargo check --features v2_4
  - cargo check --features v2_5
  - cargo check --features v2_6
  - cargo check --features v2_7
  - cd examples
  - cargo build
