language: rust
rust:
- nightly
- stable
sudo: true
env:
  global:
    - secure: UbBFC1c7nxMQCJ+AIsU2PYFnNvh33UPeeobGWE89fIyV4HQ7k3IMX7zZKKCiRuHC5AZzVa3t2jEq/yQlBpk1Opy0rAU4S/F+RcygVlsfOXGDtZkdWpBekVhjAsxSDLzCWjLhlajje3jzFLu/5UomJweubmmZ0xtX0gx8zU0nPhU=
    - LD_LIBRARY_PATH=/usr/local/lib
install:
  - sudo apt-get install libgsl0-dev
script:
  - rustc --version
  - RUST_BACKTRACE=1 cargo build
  - RUST_BACKTRACE=1 cargo doc
  - RUST_BACKTRACE=1 cargo test
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
