language: rust
rust:
- nightly
- stable
sudo: true
env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
install:
  - sudo apt-get -qq update
  - sudo apt-get install libgsl0-dev
script:
  - rustc --version
  - RUST_BACKTRACE=1 cargo build
  - RUST_BACKTRACE=1 cargo doc
  - RUST_BACKTRACE=1 cargo test
  - cd examples
  - cargo build
