[package]

name = "rust-GSL"
version = "0.1.0"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

[lib]

name = "rgsl"
crate-type = ["dylib", "rlib"]

[[bin]]

name = "simple"
path = "examples/simple/main.rs"

[[bin]]

name = "rng"
path = "examples/rng/main.rs"

[[bin]]

name = "random_number_distribution"
path = "examples/random_number_distribution/main.rs"

[[bin]]

name = "permutation"
path = "examples/permutation/main.rs"

[[bin]]

name = "sorting"
path = "examples/sorting/main.rs"