[package]

name = "GSL"
version = "0.4.24"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

description = "A rust binding for the GSL (the GNU scientific library)"
repository = "https://github.com/GuillaumeGomez/rust-GSL"
documentation = "http://rust-ci.org/GuillaumeGomez/rust-GSL/doc/rgsl/"
readme = "README.md"
keywords = ["mathematics", "library", "GSL"]
license = "GPL-3.0+"

[dependencies]
c_vec = "~1.0"
num = "*"
libc = "*"

[lib]

name = "rgsl"
crate-type = ["dylib", "rlib"]
