[package]

name = "rust-GSL"
version = "0.4.9"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

[lib]

name = "rgsl"
crate-type = ["dylib", "rlib"]

[[bin]]

name = "simple"
path = "examples/simple/main.rs"

[[bin]]

name = "rng"
path = "examples/rng/main.rs"

[[bin]]

name = "random_number_distribution"
path = "examples/random_number_distribution/main.rs"

[[bin]]

name = "permutation"
path = "examples/permutation/main.rs"

[[bin]]

name = "sorting"
path = "examples/sorting/main.rs"

[[bin]]

name = "chebyshev_approximation"
path = "examples/chebyshev_approximation/main.rs"

[[bin]]

name = "combination"
path = "examples/combination/main.rs"

[[bin]]

name = "roots_of_polynomial"
path = "examples/roots_of_polynomial/main.rs"

[[bin]]

name = "numerical_differentiation"
path = "examples/numerical_differentiation/main.rs"

[[bin]]

name = "radix"
path = "examples/radix/main.rs"

[[bin]]

name = "integration"
path = "examples/integration/main.rs"

[[bin]]

name = "interpolation"
path = "examples/interpolation/main.rs"

[[bin]]

name = "linear_algebra"
path = "examples/linear_algebra/main.rs"

[[bin]]

name = "minimization"
path = "examples/minimization/main.rs"

[[bin]]

name = "monte_carlo"
path = "examples/monte_carlo/main.rs"

[[bin]]

name = "n_tuples"
path = "examples/n_tuples/main.rs"

[[bin]]

name = "multisets"
path = "examples/multisets/main.rs"

[[bin]]

name = "ordinary_differential_equations"
path = "examples/ordinary_differential_equations/main.rs"

[[bin]]

name = "qrng"
path = "examples/qrng/main.rs"