[package]
name = "rgsl-examples"
version = "0.4.19"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

[dependencies]
c_vec = "*"
num = "*"
libc = "*"

[dependencies.GSL]
path = "../"

[[bin]]

name = "simple"
path = "simple/main.rs"

[[bin]]

name = "rng"
path = "rng/main.rs"

[[bin]]

name = "random_number_distribution"
path = "random_number_distribution/main.rs"

[[bin]]

name = "permutation"
path = "permutation/main.rs"

[[bin]]

name = "sorting"
path = "sorting/main.rs"

[[bin]]

name = "chebyshev_approximation"
path = "chebyshev_approximation/main.rs"

[[bin]]

name = "combination"
path = "combination/main.rs"

[[bin]]

name = "roots_of_polynomial"
path = "roots_of_polynomial/main.rs"

[[bin]]

name = "numerical_differentiation"
path = "numerical_differentiation/main.rs"

[[bin]]

name = "radix"
path = "radix/main.rs"

[[bin]]

name = "integration"
path = "integration/main.rs"

[[bin]]

name = "interpolation"
path = "interpolation/main.rs"

[[bin]]

name = "linear_algebra"
path = "linear_algebra/main.rs"

[[bin]]

name = "minimization"
path = "minimization/main.rs"

[[bin]]

name = "monte_carlo"
path = "monte_carlo/main.rs"

[[bin]]

name = "n_tuples"
path = "n_tuples/main.rs"

[[bin]]

name = "multisets"
path = "multisets/main.rs"

[[bin]]

name = "ordinary_differential_equations"
path = "ordinary_differential_equations/main.rs"

[[bin]]

name = "qrng"
path = "qrng/main.rs"

[[bin]]

name = "statistics"
path = "statistics/main.rs"

[[bin]]

name = "series_acceleration"
path = "series_acceleration/main.rs"

[[bin]]

name = "wavelet_transforms"
path = "wavelet_transforms/main.rs"

[[bin]]

name = "physical_constant"
path = "physical_constant/main.rs"

[[bin]]

name = "vectors_and_matrices"
path = "vectors_and_matrices/main.rs"

[[bin]]

name = "multifit_solver"
path = "multifit_solver/main.rs"