[package]
name = "regen"
version = "1.0.0"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

description = "Binary to regen FFI"
repository = "https://github.com/GuillaumeGomez/rust-GSL"
license = "MIT"

[dependencies]
bindgen = "0.55"
tempfile = "3.1"

[[bin]]
name = "regen"
doc = false
test = false
path = "regen.rs"
